# Array Creation

In [1]:
import numpy as np

In [2]:
listarray = np.array([[1,4,6],[3,5,8],[7,5,3]])

In [3]:
listarray

array([[1, 4, 6],
       [3, 5, 8],
       [7, 5, 3]])

In [4]:
listarray.dtype

dtype('int32')

In [5]:
listarray.shape

(3, 3)

In [6]:
listarray.size

9

In [7]:
listarray[1,1]=45

In [8]:
listarray

array([[ 1,  4,  6],
       [ 3, 45,  8],
       [ 7,  5,  3]])

In [9]:
np.array({35,65,25})

array({65, 35, 25}, dtype=object)

In [10]:
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
rng = np.arange(15)
# this will give array from 0 to 14

In [12]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [13]:
lspace = np.linspace(1,5,12)
# this will give equal linearly divided 12 elements from 1 to 5

In [14]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [15]:
np.linspace(1,20,10)


array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [16]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [17]:
emp = np.empty((4,6))
# gives array of random elements

In [18]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23047842e-307, 2.22526399e-307, 6.23053614e-307],
       [7.56592338e-307, 1.60216183e-306, 7.56602523e-307,
        3.56043054e-307, 1.37961641e-306, 2.22518251e-306],
       [1.33511969e-306, 6.23037317e-307, 6.23053954e-307,
        9.34609790e-307, 8.45593934e-307, 9.34600963e-307],
       [1.86921143e-306, 6.23061763e-307, 9.34593493e-307,
        7.56602524e-307, 2.22522596e-306, 3.91786943e-317]])

In [19]:
emp_like = np.empty_like(lspace)
# gives the elements of array which we had already made with the same size,
# thiss is used for the efficiency

In [20]:
emp_like


array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [21]:
ide = np.identity(5)
# creates identity matrix 

In [22]:
ide


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
ide.shape

(5, 5)

**important functions

In [24]:
arr = np.arange(99)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
# reshape function
# it is only used for the same no. of elements, for eg here we have 99 elements so we can reshape it only when the condition satisfies
# we can have 33x3 and not 31x3

In [27]:
arr.reshape(3,33)


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [28]:
arr
#this is showing 1D array bcoz we haven't assigned its value to'arr'

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [29]:
arr = arr.reshape(3,33)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr = arr.ravel()
#this will make the array back to its earlier version ie. 1D array of 99 elements

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

#axis in numpy

* 2D arrays have 2 axes ie. 'x' and 'y'


* in numpy, we call it '0' and '1'

* axis 0 is for rows and axis 1 is for columns(for 2D array)
* 1D array only have axis 0


In [33]:
x=[[1,2,3],[4,5,6],[6,7,8]]

In [34]:
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [35]:
ar.sum(axis=0)
# this will goive sum of axis 0. 
# since axis 0 is for rows , it will give sum of each rows

array([11, 14, 17])

In [36]:
ar.sum(axis=1)
# similarly for axis 1 it will give sum for each columns

array([ 6, 15, 21])

# Attributes and Methods in Numpy


In [38]:
ar.T
# Transpose of Matrix, ie. row becomes column and column becomes row

array([[1, 4, 6],
       [2, 5, 7],
       [3, 6, 8]])

In [39]:
ar.flat

In [40]:
for item in ar.flat:
    print(item)
    
# this will print all the items in ar    

1
2
3
4
5
6
6
7
8


In [41]:
ar.ndim

# gives no. of dimensions of array

2

In [42]:
ar.size

# gives no. of elements in array

9

In [44]:
ar.nbytes

# gives bytes consumed

36

In [45]:
one = np.array([1,4,3,56,3])

In [46]:
one.argmax()

# since we had put parenthesis here that means it will work as method and 
# earlier without parenthesis we're using that as attributes

# argmax gives the index number where the highest element is


3

In [47]:
one.argmin()

# this will give the index where the smallest element lies

0

In [48]:
one.argsort()

# this gives the order of indices in ascending order

array([0, 2, 4, 1, 3], dtype=int64)

** For 2D array

In [49]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [50]:
ar.argmin()


0

In [51]:
ar.argmax()

8

In [52]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [53]:
ar.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [54]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [55]:
ar.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [56]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)

In [57]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [58]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 6, 7, 8])

In [59]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [6],
       [7],
       [8]])

# Mathematical Operations in Numpy

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [61]:
ar2 = np.array([[7, 5, 3],
       [4, 3, 6],
       [1, 9, 4]])

In [62]:
ar2

array([[7, 5, 3],
       [4, 3, 6],
       [1, 9, 4]])

In [63]:
ar + ar2

array([[ 8,  7,  6],
       [ 8,  8, 12],
       [ 7, 16, 12]])

In [64]:
ar * ar2


array([[ 7, 10,  9],
       [16, 15, 36],
       [ 6, 63, 32]])

In [65]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.44948974, 2.64575131, 2.82842712]])

In [66]:
ar.sum()

42

In [67]:
ar.max

<function ndarray.max>

In [68]:
ar.max()

8

In [69]:
ar.min()

1

In [70]:
# to find the elements in array

np.where(ar>4)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [71]:
np.count_nonzero(ar)

9

In [72]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [73]:
ar[1,2]=0
ar[1,1]=0

In [74]:
np.nonzero(ar)


(array([0, 0, 0, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 0, 1, 2], dtype=int64))

In [76]:
import sys

# goodbye! see you again